config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  get "/restricted", to: "pages#restricted"
  get "/listings", to: "listings#index", as: "listings"
  post "/listings", to: "listings#create"
  get "listings/new", to: "listings#new", as: "new_listing"
  get "listings/:id", to: "listings#show", as: "listing"
  put "listings/:id", to: "listings#update"
  patch "listings/:id", to: "listings#update"
  delete "listings/:id", to: "listings#destroy", as: "delete_listing"
  get "listings/:id/edit", to: "listings#edit", as: "edit_listing"
  get "payments/success/:id", to: "payments#success", as: "payments_success"
  post "/payments/webhook", to: "payments#webhook"
  post "payments", to: "payments#create_checkout_session", as: "create_checkout_session"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :listings
    
end

app/models/dietry.rb
class Dietry < ApplicationRecord
    has_many :listings_dietries
    has_many :listings, through: :listings_dietries
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :listings_dietries, dependent: :destroy
  has_many :dietries, through: :listings_dietries
  has_one_attached :picture

  #validations for listings to be saved
  validates :title, :description, :price, presence: true
  validates :title, length: {minimum: 4}

  #sanitise data with lifecycle hooks
  before_save :remove_whitespace
  before_save :replace_word
  before_validation :convert_price_to_cents, if: :price_changed?

  private

  #removing whitespace 
  def remove_whitespace
    self.title = self.title.strip
    self.description =self.description.strip
  end

  #removing the word EXPENSIVE because this is an affordable community app!! no big $$$ items here
  def replace_word
    self.title = self.title.gsub(/expensive/i, "affordable")
    self.description = self.title.gsub(/expensive/i, "affordable")
  end

  def convert_price_to_cents
    self.price = (self.attributes_before_type_cast["price"].to_f * 100).round
  end


end

app/models/listings_dietry.rb
class ListingsDietry < ApplicationRecord
  belongs_to :listing
  belongs_to :dietry
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :listing
  belongs_to :buyer, foreign_key: "buyer_id", class_name: "User"
  belongs_to :seller, foreign_key: "seller_id", class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :listings
  has_many :sold_orders, foreign_key: "seller_id", class_name: "Order"
  has_many :bought_orders, foreign_key: "buyer_id", class_name: "Order"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  #this before action below is what secures the listings
  before_action :authorize_user, only: [:edit, :update, :destroy]
  before_action :set_form_vars, only: [:new, :edit]

    #adding in eager load here creeates bugs elsewhere...
  def index
    @listings = Listing.all
  end

  def show

  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = current_user.listings.new(listing_params)
    if @listing.save
      redirect_to @listing, notice: "You have successfully listed your food!"
    else
      set_form_vars
      render "new", alert: "something went wrong :( "
    end
  end

  def edit
  
  end

  def update
    @listing.update(listing_params)
    if @listing.save
      redirect_to @listing, notice: "Your food listing has now been updated"
    else
      set_form_vars
      render "edit", alert: "something went wrong :( "
    end
  end 

  def destory
    @listing.destroy
    redirect_to listings_path, notice: "the food was deleted!"

  end

  private

  def listing_params
    params.require(:listing).permit(:title, :price, :category_id, :description, :picture, dietry_ids: [])
  end

  def authorize_user
    if @listing.user_id != current_user.id
      flash[:alert] = "Nuh ah! you arent allowed"
      redirect_to listings_path
    end
  end

  def set_listing
    @listing = Listing.find(params[:id])
  end

  def set_form_vars
    @categories = Category.all
    @dietries = Dietry.all
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: [:show]

  def index
    @orders = Order.all
  end

  def show

  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    before_action :authenticate_user!, only: [:restricted]
    
    def home

    end

    def restricted

    end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
    skip_before_action :verify_authenticity_token, only: [:webhook]

    def success
      @order = Order.find_by(listing_id: params[:id])
    end

    def create_checkout_session
        @listing = Listing.find(params[:id])

        session = Stripe::Checkout::Session.create(
            payment_method_types: ["card"],
            customer_email:current_user && current_user.email,
            line_items: [
              {
                name: @listing.title,
                description: @listing.description,
                amount: @listing.price,
                currency: "aud",
                quantity: 1
              }
            ],
            payment_intent_data: {
              metadata: {
                user_id: current_user && current_user.id,
                listing_id: @listing.id
              }
            },
            success_url: "#{root_url}payments/success/#{@listing.id}",
            cancel_url: root_url
          )
      
          @session_id = session.id
    end

    def webhook

        begin 
            payload = request.raw_post
            header = request.headers['HTTP_STRIPE_SIGNATURE']
            secret = Rails.application.credentials.dig(:stripe,:webhook_signing_secret) 
            event = Stripe::Webhook.construct_event(payload, header, secret)
        rescue Stripe::SignatureVerificationError => e
            render json: {error: "Unauthorised"}, status: 403
            return
        rescue JSON::ParserError => e
            render json: {error: "Bad request"}, status: 422
            return
        end

        #tracking out purchase info

        payment_intent_id = event.data.object.payment_intent
        payment = Stripe::PaymentIntent.retrieve(payment_intent_id)
        listing_id = payment.metadata.listing_id
        buyer_id = payment.metadata.user_id
        pp payment.charges.data[0].receipt_url
        @listing = Listing.find(listing_id)
        @listing.update(sold: true)

        #create order/purchase and track info
        Order.create(listing_id: listing_id, buyer_id: buyer_id, seller_id: @listing.user_id, payment_id: payment_intent_id, receipt_url: payment.charges.data[0].receipt_url )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def select_alert_subclass(input)
        case input
        when "notice"
            return "success"
        when "alert"
            return "warning"
        when "error"
            return "danger"
        else 
            return "info"
        end
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
    # def format_condition(condition)
    #     arr = condition.split("_").map do |word|
    #       word.capitalize
    #     end
    #     arr.join(" ")
    # end
    # taking out underscore and capitalizing first letter of word

    def format_price(price)
        "$#{price/ 100.00}"
    end 
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marketplace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3/"></script>
  </head>

  <body>
   <%flash.each do |key, value|%>
      <div class="alert alert-<%=select_alert_subclass(key)%> alert-dismissable fade show" role="alert">
        <%=value%>
        <button type="button" class="close" data-dismiss="alert" aria-label="close"> <span aria-hidden="true">&times;</span> </button>
      </div>
   <%end%>
    <%= render "shared/navbar"%>
    <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<%=form_with model: @listing, local: true do |f|%>
    <%if @listing.errors.any?%>
        <div class="alert alert-error alert-dismissable fade show">
            <h4><%=pluralize(@listing.errors.count, "error")%> stopped you from adding your food! </h4>
            <ul>
                <%@listing.errors.full_messages.each do |message|%>
                    <li><%=message%></li>
                <%end%>
            </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="close">
            <span aria-hidden="true">&times;</span>
        </button>
        </div> 
    <%end%>


    <div class="container">
        <div class="form-group mb-3">
            <%=f.label :title, class: "form-label"%>
            <%=f.text_field :title%>
        </div>

        <div class="form-group mb-3">
            <%=f.label :price, class: "form-label"%>
            <%=f.number_field :price, step:"0.01"%>
        </div>

        <div class="form-group mb-3">
            <%=f.label :category_id, class: "form-label"%>
            <%=f.select :category_id, @categories.map {|c| [c.name, c.id]}, class: "form-select"%>
        </div>

        <h6 class="mb-3 ml-2">dietry info:</h6>
        <div class="form-check form-check-line mb-3 ml-2">
            <%=f.collection_check_boxes :dietry_ids, @dietries, :id, :name do |b|%>
                <%=b.label class: "form-check-label"%>
                <%=b.check_box class: "form-check-line mr-2"%>
            <%end%>    
        </div>

        <div class="form-group mb-3">
            <%=f.label :picture, class: "form-label"%>
            <%=f.file_field :picture, accept: "image/png,image/jpg,image/jpeg", class: "form-select"%>
        </div>

        <div class="form-group mb-1">
            <%=f.label :description, class: "form-label"%>
            <%=f.text_area :description, class: "form-control"%>
        </div>

        <div class="actions">
            <%=f.submit%>
         </div>
    </div>

<%end%>

app/views/listings/edit.html.erb
<h1> update food listing </h1>
<%= render "form"%>
<%link_to "Home", root_path%>

app/views/listings/index.html.erb
<h1 class="hero-title text-center">all food</h1>

<section class="container">
    <div class="row row-cols-sm-1 row-cols-md-2 row-cols-lg-4">
        <%@listings.each do |listing|%>
        <div class="col mb-4">
             <div class="card bg-success text-white border-dark h-100">
                  <%if listing.picture.attached?%>
                      <%=image_tag listing.picture, class:"thumbnail card-img top", alt: listing.title%>
                  <%else%>
                      <%=image_tag "foodtubs.jpg", class:"thumbnail card-img top", alt: "tubs of cooked food"%>
                  <%end%>
                 <div class="card-body">
                     <h5><%=listing.title%></h5>
                      <p class="card-text text-white"><%=listing.description%></p>
                         <div class="d-flex justify-content-between">
                         <%=link_to "details", listing_path(listing.id), class: "btn btn-white text-dark"%>
                           <h5><%=format_price(listing.price)%></h5>
                      </div>

                  </div>
              </div>
         </div>

            <%end%>
        </div>

</section>

app/views/listings/new.html.erb
<div class="container bg-success text-white">
  <div class="card-body">
    <h1> list your food </h1>
    <%= render "form"%>
    <%link_to "Home", root_path%>
  </div>
</div>

app/views/listings/show.html.erb
<section class="container d-flex flex-colum flex-md-row px-2 my-2 my-md-5">
    <div class="content col-12 col-md-7 col-lg-8 p-0 pr-md-3">
        <div class="col-12 p-0 main-preview mb-4">
            <%if @listing.picture.attached?%>
            <%=image_tag @listing.picture, class:"thumbnail card-img top", alt: @listing.title%>
            <%else%>
            <%=image_tag "foodtubs.jpg", class:"thumbnail card-img top", alt: "tubs of cooked food"%>
            <%end%>
        </div>
    </div>
    <div class="sidebar col-lg-4 p-0 mx-2 d-md-block">
        <h2 class="mb-sm-2 mb-md-5"><%=@listing.title%></h2>
        <p class="card-text text-secondary"><%=@listing.description%></p>

        <h6 class="text-muted mb-3">Category: <%=@listing.category.name%></h6>

        <h6 class="text-muted">Price: <%=format_price(@listing.price)%></h6>
        <%@listing.dietries.each do |dietry|%>
            <span class="badge badge-pill badge-success mb-3"><%=dietry.name%></span>
        <%end%>

        <%if current_user && @listing.sold == false %>
            <%=button_to "buy me #{format_price(@listing.price)}", 
            create_checkout_session_path,
            remote: true,
            method: :post,
            params: {id: @listing.id},
            class: "btn btn-success btn-sm btn-block mb-3 pr-2",
            data: {disable_with: "Loading...."}%>
        <%elsif @listing.sold%>
        <button class= "btn btn-secondary btn-sm btn-block mb-3 pr-2" disabled>SOLD</button>
        <%else%>
        <%=button_to "sign in to buy", new_user_session_path, class: "btn btn-outline-success"%>
        <%end%>
            <div class="container">
                <%if current_user && current_user.id == @listing.user_id%>
                     <div class="d-flex justify-content-end">
                        <%= link_to "edit", edit_listing_path(@listing.id), class: "btn btn-outline-info btn-sm mr-2"%>
                        <%= link_to "delete", @listing, method: :delete, data: {confirm: "are you reeaaaly sure you want to delete this??"}, class: "btn btn-outline-warning btn-sm mr-2"%>
                    </div>
                 <%end%>      
            </div>
    </div>

</section>

app/views/pages/home.html.erb
<div class="card text-center">
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p>A community run food re-distribution network, for everyone.</p>
    </blockquote>
      <%=link_to "join the community", new_user_session_path, class: "btn btn-outline-success bth-sm mr-2"%>
      <%# <%= link_to "Sign up", new_registration_path(resource_name) %> 
  </div>
</div>
</div>
<div class="main-background">

</div>

app/views/pages/restricted.html.erb
<p> you can only be here if you are logged in </p>

app/views/payments/create_checkout_session.js.erb
    const stripe = Stripe("<%=Rails.application.credentials.dig(:stripe, :public_key)%>");

    stripe.redirectToCheckout({
        sessionId: "<%=@session_id%>"
    })

app/views/payments/success.html.erb
<p> thank you so much for supporting your community and buying <%=@order.listing.title%> </p>
<%=link_to "view your receipt", @order.receipt_url%>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light navbar-expand-md" style="background-color: #d2f0c9;">
    <div class="container-fluid">
        <%=link_to "plate to plate", root_path, class: "text-success navbar-brand"%>
    </div>

    <ul class="navbar-nav mr-5-lg">
        <li  class="nav-item">
            <%=link_to "all food", listings_path, class: "nav-link"%>
        </li>
        <%if user_signed_in?%>
        <li  class="nav-item">
            <%=link_to "list food", new_listing_path, class: "nav-link"%>
        </li>
        <li  class="nav-item">
            <%=link_to "sign out", destroy_user_session_path, method: :delete, class: "nav-link"%>
        </li>
        <%else%>
        <li  class="nav-item">
            <%=link_to "sign In", new_user_session_path, class: "nav-link"%>
        </li>
        <%end%>

    </ul>

</nav>